version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: weatherstation
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: weatherstation_app
    restart: always
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_URL: jdbc:mysql://mysql:${MYSQL_PORT:3306}/weatherstation?allowPublicKeyRetrieval=true&useSSL=false
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      APP_SECURITY_USERNAME: ${APP_ADMIN_USERNAME}
      APP_SECURITY_PASSWORD: ${APP_ADMIN_PASSWORD}


volumes:
  mysql_data:
